import '../models/book.dart';

final List<Book> dummyBooks = [
  Book(
    title: 'The Shadow Knight',
    author: 'A. R. Valen',
    genre: 'Fantasy',
    coverUrl: 'assets/images/knight.jpg',
    synopsis: 'A cursed warrior must reclaim his honor in a kingdom ruled by fear.',
    rating: 4.8,
    isFavorite: true,
    isRead: true,
    content: 'Chapter 1: The wind howled through the valley as the knight stepped into the ruins...',
    chapterCount: 12,
    releaseDate: '2023-06-15',
    coverArtist: 'Luna Ardent',
  ),
  Book(
    title: 'Cyber Healer',
    author: 'N. K. Orion',
    genre: 'Sci-Fi',
    coverUrl: 'assets/images/healer.jpg',
    synopsis: 'In a future ruled by machines, one medic dares to rewrite the code of fate.',
    rating: 4.5,
    isFavorite: false,
    isRead: true,
    content: 'Chapter 1: Neon lights flickered as Nova jacked into the grid...',
    chapterCount: 9,
    releaseDate: '2024-01-22',
    coverArtist: 'PixelForge Studio',
  ),
  Book(
    title: 'Whispers of the Wizard',
    author: 'L. M. Hart',
    genre: 'Mystery',
    coverUrl: 'assets/images/wizard.jpg',
    synopsis: 'A forgotten spellbook reveals secrets that could unravel reality itself.',
    rating: 4.2,
    isFavorite: true,
    isRead: false,
    content: 'Chapter 1: The fog rolled in thick as the wizard opened the ancient tome...',
    chapterCount: 15,
    releaseDate: '2022-10-05',
    coverArtist: 'MysticBrush',
  ),
  Book(
    title: 'Tankborn',
    author: 'J. S. Kade',
    genre: 'Action',
    coverUrl: 'assets/images/tank.jpg',
    synopsis: 'Built for war, trained for peace. One soldier must choose his destiny.',
    rating: 4.6,
    isFavorite: false,
    isRead: false,
    content: 'Chapter 1: The ground shook as the tank unit rolled into the city...',
    chapterCount: 10,
    releaseDate: '2023-03-11',
    coverArtist: 'SteelInk Studio',
  ),
  Book(
    title: 'Assassin’s Echo',
    author: 'T. K. Solas',
    genre: 'Thriller',
    coverUrl: 'assets/images/assassin.jpg',
    synopsis: 'Every kill leaves a trace. And someone is following the echoes.',
    rating: 4.9,
    isFavorite: true,
    isRead: true,
    content: 'Chapter 1: The blade whispered as it sliced through the silence...',
    chapterCount: 8,
    releaseDate: '2025-01-01',
    coverArtist: 'EchoGraphix',
  ),
];
